/* Automatically generated by create_config - do not modify */
#define TARGET_I386 1
#define TARGET_NAME "i386"
#define TARGET_I386 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-i386"
#define CONFIG_LINUX_USER 1
#define CONFIG_I386_DIS 1
#define CONFIG_I386_DIS 1
