# Automatically generated by configure - do not modify
TARGET_I386=y
TARGET_NAME=i386
TARGET_BASE_ARCH=i386
TARGET_ABI_DIR=i386
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-i386"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/dungnguyen/UAFuzz/binsec/src/uafuzz/afl-2.52b/qemu_mode_uafuzz/qemu-2.10.0/gdb-xml/i386-32bit.xml /home/dungnguyen/UAFuzz/binsec/src/uafuzz/afl-2.52b/qemu_mode_uafuzz/qemu-2.10.0/gdb-xml/i386-32bit-core.xml /home/dungnguyen/UAFuzz/binsec/src/uafuzz/afl-2.52b/qemu_mode_uafuzz/qemu-2.10.0/gdb-xml/i386-32bit-sse.xml
CONFIG_I386_DIS=y
CONFIG_I386_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
