PINSEC_BUILD_FILES = CMakeLists.txt Targets.mk

PINSEC_LICENSE_CEA_IMAG =
PINSEC_LICENSE_IMAG =
PINSEC_LICENSE_CEA =
PINSEC_EXTERNAL =

PINSEC_SRC = src

PINSEC_ROOT_HDR_CEA_IMAG = callback instrumentation \
	call_infos concrete_actions syscall_infos utils
PINSEC_ROOT_SRC_CEA_IMAG = main
PINSEC_ROOT_HDR_FILES = \
	$(PINSEC_ROOT_HDR_IMAG) \
	$(PINSEC_ROOT_HDR_CEA_IMAG)
PINSEC_ROOT_SRC_FILES = \
	$(PINSEC_ROOT_HDR_FILES) \
	$(PINSEC_ROOT_SRC_CEA_IMAG)
PINSEC_ROOT_FILES = \
	$(PINSEC_ROOT_HDR_FILES:%=$(PINSEC_SRC)/%.hpp) \
	$(PINSEC_ROOT_SRC_FILES:%=$(PINSEC_SRC)/%.cpp) 

PINSEC_LICENSE_CEA_IMAG += \
	$(PINSEC_ROOT_SRC_CEA_IMAG:%=$(PINSEC_SRC)/%.cpp) \
	$(PINSEC_ROOT_HDR_CEA_IMAG:%=$(PINSEC_SRC)/%.hpp) \
	$(PINSEC_ROOT_HDR_CEA_IMAG:%=$(PINSEC_SRC)/%.cpp) 
PINSEC_LICENSE_IMAG += \
	$(PINSEC_ROOT_HDR_IMAG:%=$(PINSEC_SRC)/%.hpp) \
	$(PINSEC_ROOT_HDR_IMAG:%=$(PINSEC_SRC)/%.cpp) 



PINSEC_INOUT_DIR = $(PINSEC_SRC)/inout
PINSEC_INOUT_HDR_FILES = printer trace
PINSEC_INOUT_SRC_FILES = $(PINSEC_INOUT_HDR_FILES)
PINSEC_INOUT_FILES = \
	$(PINSEC_INOUT_SRC_FILES:%=$(PINSEC_INOUT_DIR)/%.cpp) \
	$(PINSEC_INOUT_HDR_FILES:%=$(PINSEC_INOUT_DIR)/%.hpp)
PINSEC_LICENSE_CEA_IMAG += \
	$(PINSEC_INOUT_FILES)


# These files have been taken from another MIT-licensed project 
PINSEC_LIBDIR = $(PINSEC_SRC)/lib/json2pb
PINSEC_LIB_HDR_FILES = bin2ascii json2pb
PINSEC_LIB_SRC_FILES = json2pb
PINSEC_LIB_FILES = \
	$(PINSEC_LIB_SRC_FILES:%=$(PINSEC_LIBDIR)/%.cc) \
	$(PINSEC_LIB_HDR_FILES:%=$(PINSEC_LIBDIR)/%.h)
PINSEC_EXTERNAL += $(PINSEC_LIB_FILES)


PINSEC_SERVER_DIR = $(PINSEC_SRC)/server
PINSEC_SERVER_SRC_FILES = server_callback server_linux server_windows
PINSEC_SERVER_HDR_FILES = server server_callback
PINSEC_SERVER_FILES = \
	$(PINSEC_SERVER_HDR_FILES:%=$(PINSEC_SERVER_DIR)/%.hpp) \
	$(PINSEC_SERVER_SRC_FILES:%=$(PINSEC_SERVER_DIR)/%.cpp) 
PINSEC_LICENSE_CEA_IMAG += \
	$(PINSEC_SERVER_FILES)


PINSEC_TYPES_DIR = $(PINSEC_SRC)/types
PINSEC_TYPES_SRC_FILES = instruction 
PINSEC_TYPES_HDR_FILES = instruction types
PINSEC_TYPES_FILES = \
	$(PINSEC_TYPES_HDR_FILES:%=$(PINSEC_TYPES_DIR)/%.hpp) \
	$(PINSEC_TYPES_SRC_FILES:%=$(PINSEC_TYPES_DIR)/%.cpp) 
PINSEC_LICENSE_CEA_IMAG += \
	$(PINSEC_TYPES_FILES)

PINSEC_DISTRIB_FILES = \
	$(PINSEC_BUILD_FILES) \
	$(PINSEC_LIB_FILES) \
	$(PINSEC_ROOT_FILES) \
	$(PINSEC_SERVER_FILES) \
	$(PINSEC_TYPES_FILES) \
	$(PINSEC_INOUT_FILES)
