# Automatically generated by configure - do not modify
SRC_PATH=/home/dungnguyen/UAFuzz/binsec/src/uafuzz/afl-2.52b/qemu_mode_aflgob/qemu-2.10.0/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
