=head1 NAME

qemu-ga-ref - QEMU Guest Agent Protocol Reference

=head1 DESCRIPTION


General note concerning the use of guest agent interfaces:

"unsupported" is a higher-level error than the errors that individual
commands might document. The caller should always be prepared to receive
QERR_UNSUPPORTED, even if the given command doesn't specify it, or doesn't
document any failure mode at all.



B<guest-sync-delimited>  (Command)
Echo back a unique integer value, and prepend to response a
leading sentinel byte (0xFF) the client can check scan for.

This is used by clients talking to the guest agent over the
wire to ensure the stream is in sync and doesn't contain stale
data from previous client. It must be issued upon initial
connection, and after any client-side timeouts (including
timeouts on receiving a response to this command).

After issuing this request, all guest agent responses should be
ignored until the response containing the unique integer value
the client passed in is returned. Receival of the 0xFF sentinel
byte must be handled as an indication that the client's
lexer/tokenizer/parser state should be flushed/reset in
preparation for reliably receiving the subsequent response. As
an optimization, clients may opt to ignore all data until a
sentinel value is receiving to avoid unnecessary processing of
stale data.

Similarly, clients should also precede this B<request>
with a 0xFF byte to make sure the guest agent flushes any
partially read JSON data from a previous client connection.

B<Arguments:>

=over 4


=item C<id: int>

randomly generated 64-bit integer

=back



B<Returns:>
The unique integer id passed in by the client

B<Since:>
1.1






B<guest-sync>  (Command)
Echo back a unique integer value

This is used by clients talking to the guest agent over the
wire to ensure the stream is in sync and doesn't contain stale
data from previous client. All guest agent responses should be
ignored until the provided unique integer value is returned,
and it is up to the client to handle stale whole or
partially-delivered JSON text in such a way that this response
can be obtained.

In cases where a partial stale response was previously
received by the client, this cannot always be done reliably.
One particular scenario being if qemu-ga responses are fed
character-by-character into a JSON parser. In these situations,
using guest-sync-delimited may be optimal.

For clients that fetch responses line by line and convert them
to JSON objects, guest-sync should be sufficient, but note that
in cases where the channel is dirty some attempts at parsing the
response may result in a parser error.

Such clients should also precede this command
with a 0xFF byte to make sure the guest agent flushes any
partially read JSON data from a previous session.

B<Arguments:>

=over 4


=item C<id: int>

randomly generated 64-bit integer

=back



B<Returns:>
The unique integer id passed in by the client

B<Since:>
0.15.0






B<guest-ping>  (Command)
Ping the guest agent, a non-error return implies success


B<Since:>
0.15.0






B<guest-get-time>  (Command)
Get the information about guest's System Time relative to
the Epoch of 1970-01-01 in UTC.


B<Returns:>
Time in nanoseconds.

B<Since:>
1.5






B<guest-set-time>  (Command)
Set guest time.

When a guest is paused or migrated to a file then loaded
from that file, the guest OS has no idea that there
was a big gap in the time. Depending on how long the
gap was, NTP might not be able to resynchronize the
guest.

This command tries to set guest's System Time to the
given value, then sets the Hardware Clock (RTC) to the
current System Time. This will make it easier for a guest
to resynchronize without waiting for NTP. If no C<time> is
specified, then the time to set is read from RTC. However,
this may not be supported on all platforms (i.e. Windows).
If that's the case users are advised to always pass a
value.

B<Arguments:>

=over 4


=item C<time: int> (optional)

time of nanoseconds, relative to the Epoch
of 1970-01-01 in UTC.

=back



B<Returns:>
Nothing on success.

B<Since:>
1.5






B<GuestAgentCommandInfo> (Object)


Information about guest agent commands.

B<Members:>

=over 4


=item C<name: string>

name of the command

=item C<enabled: boolean>

whether command is currently enabled by guest admin

=item C<success-response: boolean>

whether command returns a response on success
(since 1.7)

=back



B<Since:>
1.1.0






B<GuestAgentInfo> (Object)


Information about guest agent.

B<Members:>

=over 4


=item C<version: string>

guest agent version

=item C<supported_commands: array of GuestAgentCommandInfo>

Information about guest agent commands

=back



B<Since:>
0.15.0






B<guest-info>  (Command)
Get some information about the guest agent.


B<Returns:>
C<GuestAgentInfo>

B<Since:>
0.15.0






B<guest-shutdown>  (Command)
Initiate guest-activated shutdown. Note: this is an asynchronous
shutdown request, with no guarantee of successful shutdown.

B<Arguments:>

=over 4


=item C<mode: string> (optional)

"halt", "powerdown" (default), or "reboot"

=back

This command does NOT return a response on success. Success condition
is indicated by the VM exiting with a zero exit status or, when
running with --no-shutdown, by issuing the query-status QMP command
to confirm the VM status is "shutdown".

B<Since:>
0.15.0






B<guest-file-open>  (Command)
Open a file in the guest and retrieve a file handle for it

B<Arguments:>

=over 4


=item C<path: string>

Full path to the file in the guest to open.

=item C<mode: string> (optional)

open mode, as per fopen(), "r" is the default.

=back



B<Returns:>
Guest file handle on success.

B<Since:>
0.15.0






B<guest-file-close>  (Command)
Close an open file in the guest

B<Arguments:>

=over 4


=item C<handle: int>

filehandle returned by guest-file-open

=back



B<Returns:>
Nothing on success.

B<Since:>
0.15.0






B<GuestFileRead> (Object)


Result of guest agent file-read operation

B<Members:>

=over 4


=item C<count: int>

number of bytes read (note: count is B<before>
base64-encoding is applied)

=item C<buf-b64: string>

base64-encoded bytes read

=item C<eof: boolean>

whether EOF was encountered during read operation.

=back



B<Since:>
0.15.0






B<guest-file-read>  (Command)
Read from an open file in the guest. Data will be base64-encoded

B<Arguments:>

=over 4


=item C<handle: int>

filehandle returned by guest-file-open

=item C<count: int> (optional)

maximum number of bytes to read (default is 4KB)

=back



B<Returns:>
C<GuestFileRead> on success.

B<Since:>
0.15.0






B<GuestFileWrite> (Object)


Result of guest agent file-write operation

B<Members:>

=over 4


=item C<count: int>

number of bytes written (note: count is actual bytes
written, after base64-decoding of provided buffer)

=item C<eof: boolean>

whether EOF was encountered during write operation.

=back



B<Since:>
0.15.0






B<guest-file-write>  (Command)
Write to an open file in the guest.

B<Arguments:>

=over 4


=item C<handle: int>

filehandle returned by guest-file-open

=item C<buf-b64: string>

base64-encoded string representing data to be written

=item C<count: int> (optional)

bytes to write (actual bytes, after base64-decode),
default is all content in buf-b64 buffer after base64 decoding

=back



B<Returns:>
C<GuestFileWrite> on success.

B<Since:>
0.15.0






B<GuestFileSeek> (Object)


Result of guest agent file-seek operation

B<Members:>

=over 4


=item C<position: int>

current file position

=item C<eof: boolean>

whether EOF was encountered during file seek

=back



B<Since:>
0.15.0






B<QGASeek> (Enum)


Symbolic names for use in C<guest-file-seek>

B<Values:>

=over 4


=item C<set>

Set to the specified offset (same effect as 'whence':0)

=item C<cur>

Add offset to the current location (same effect as 'whence':1)

=item C<end>

Add offset to the end of the file (same effect as 'whence':2)

=back



B<Since:>
2.6






B<GuestFileWhence> (Alternate)


Controls the meaning of offset to C<guest-file-seek>.

B<Members:>

=over 4


=item C<value: int>

Integral value (0 for set, 1 for cur, 2 for end), available
for historical reasons, and might differ from the host's or
guest's SEEK_* values (since: 0.15)

=item C<name: QGASeek>

Symbolic name, and preferred interface

=back



B<Since:>
2.6






B<guest-file-seek>  (Command)
Seek to a position in the file, as with fseek(), and return the
current file position afterward. Also encapsulates ftell()'s
functionality, with offset=0 and whence=1.

B<Arguments:>

=over 4


=item C<handle: int>

filehandle returned by guest-file-open

=item C<offset: int>

bytes to skip over in the file stream

=item C<whence: GuestFileWhence>

Symbolic or numeric code for interpreting offset

=back



B<Returns:>
C<GuestFileSeek> on success.

B<Since:>
0.15.0






B<guest-file-flush>  (Command)
Write file changes bufferred in userspace to disk/kernel buffers

B<Arguments:>

=over 4


=item C<handle: int>

filehandle returned by guest-file-open

=back



B<Returns:>
Nothing on success.

B<Since:>
0.15.0






B<GuestFsfreezeStatus> (Enum)


An enumeration of filesystem freeze states

B<Values:>

=over 4


=item C<thawed>

filesystems thawed/unfrozen

=item C<frozen>

all non-network guest filesystems frozen

=back



B<Since:>
0.15.0






B<guest-fsfreeze-status>  (Command)
Get guest fsfreeze state. error state indicates


B<Returns:>
GuestFsfreezeStatus ("thawed", "frozen", etc., as defined below)

B<Note:>
This may fail to properly report the current state as a result of
some other guest processes having issued an fs freeze/thaw.

B<Since:>
0.15.0






B<guest-fsfreeze-freeze>  (Command)
Sync and freeze all freezable, local guest filesystems. If this
command succeeded, you may call C<guest-fsfreeze-thaw> later to
unfreeze.


B<Note:>
On Windows, the command is implemented with the help of a
Volume Shadow-copy Service DLL helper. The frozen state is limited
for up to 10 seconds by VSS.

B<Returns:>
Number of file systems currently frozen. On error, all filesystems
will be thawed.

B<Since:>
0.15.0






B<guest-fsfreeze-freeze-list>  (Command)
Sync and freeze specified guest filesystems.
See also C<guest-fsfreeze-freeze>.

B<Arguments:>

=over 4


=item C<mountpoints: array of string> (optional)

an array of mountpoints of filesystems to be frozen.
If omitted, every mounted filesystem is frozen.
Invalid mount points are ignored.

=back



B<Returns:>
Number of file systems currently frozen. On error, all filesystems
will be thawed.

B<Since:>
2.2






B<guest-fsfreeze-thaw>  (Command)
Unfreeze all frozen guest filesystems


B<Returns:>
Number of file systems thawed by this call

B<Note:>
if return value does not match the previous call to
guest-fsfreeze-freeze, this likely means some freezable
filesystems were unfrozen before this call, and that the
filesystem state may have changed before issuing this
command.

B<Since:>
0.15.0






B<GuestFilesystemTrimResult> (Object)




B<Members:>

=over 4


=item C<path: string>

path that was trimmed

=item C<error: string> (optional)

an error message when trim failed

=item C<trimmed: int> (optional)

bytes trimmed for this path

=item C<minimum: int> (optional)

reported effective minimum for this path

=back



B<Since:>
2.4






B<GuestFilesystemTrimResponse> (Object)




B<Members:>

=over 4


=item C<paths: array of GuestFilesystemTrimResult>

list of C<GuestFilesystemTrimResult> per path that was trimmed

=back



B<Since:>
2.4






B<guest-fstrim>  (Command)
Discard (or "trim") blocks which are not in use by the filesystem.

B<Arguments:>

=over 4


=item C<minimum: int> (optional)

Minimum contiguous free range to discard, in bytes. Free ranges
smaller than this may be ignored (this is a hint and the guest
may not respect it).  By increasing this value, the fstrim
operation will complete more quickly for filesystems with badly
fragmented free space, although not all blocks will be discarded.
The default value is zero, meaning "discard every free block".

=back



B<Returns:>
A C<GuestFilesystemTrimResponse> which contains the
status of all trimmed paths. (since 2.4)

B<Since:>
1.2






B<guest-suspend-disk>  (Command)
Suspend guest to disk.

This command tries to execute the scripts provided by the pm-utils package.
If it's not available, the suspend operation will be performed by manually
writing to a sysfs file.

For the best results it's strongly recommended to have the pm-utils
package installed in the guest.

This command does NOT return a response on success. There is a high chance
the command succeeded if the VM exits with a zero exit status or, when
running with --no-shutdown, by issuing the query-status QMP command to
to confirm the VM status is "shutdown". However, the VM could also exit
(or set its status to "shutdown") due to other reasons.

The following errors may be returned:
If suspend to disk is not supported, Unsupported


B<Notes:>
It's strongly recommended to issue the guest-sync command before
sending commands when the guest resumes

B<Since:>
1.1






B<guest-suspend-ram>  (Command)
Suspend guest to ram.

This command tries to execute the scripts provided by the pm-utils package.
If it's not available, the suspend operation will be performed by manually
writing to a sysfs file.

For the best results it's strongly recommended to have the pm-utils
package installed in the guest.

IMPORTANT: guest-suspend-ram requires QEMU to support the 'system_wakeup'
command.  Thus, it's B<required> to query QEMU for the presence of the
'system_wakeup' command before issuing guest-suspend-ram.

This command does NOT return a response on success. There are two options
to check for success:

=over 4


=item 1.

Wait for the SUSPEND QMP event from QEMU

=item 2.

Issue the query-status QMP command to confirm the VM status is
"suspended"


=back


The following errors may be returned:
If suspend to ram is not supported, Unsupported


B<Notes:>
It's strongly recommended to issue the guest-sync command before
sending commands when the guest resumes

B<Since:>
1.1






B<guest-suspend-hybrid>  (Command)
Save guest state to disk and suspend to ram.

This command requires the pm-utils package to be installed in the guest.

IMPORTANT: guest-suspend-hybrid requires QEMU to support the 'system_wakeup'
command.  Thus, it's B<required> to query QEMU for the presence of the
'system_wakeup' command before issuing guest-suspend-hybrid.

This command does NOT return a response on success. There are two options
to check for success:

=over 4


=item 1.

Wait for the SUSPEND QMP event from QEMU

=item 2.

Issue the query-status QMP command to confirm the VM status is
"suspended"


=back


The following errors may be returned:
If hybrid suspend is not supported, Unsupported


B<Notes:>
It's strongly recommended to issue the guest-sync command before
sending commands when the guest resumes

B<Since:>
1.1






B<GuestIpAddressType> (Enum)


An enumeration of supported IP address types

B<Values:>

=over 4


=item C<ipv4>

IP version 4

=item C<ipv6>

IP version 6

=back



B<Since:>
1.1






B<GuestIpAddress> (Object)




B<Members:>

=over 4


=item C<ip-address: string>

IP address

=item C<ip-address-type: GuestIpAddressType>

Type of C<ip-address> (e.g. ipv4, ipv6)

=item C<prefix: int>

Network prefix length of C<ip-address>

=back



B<Since:>
1.1






B<GuestNetworkInterface> (Object)




B<Members:>

=over 4


=item C<name: string>

The name of interface for which info are being delivered

=item C<hardware-address: string> (optional)

Hardware address of C<name>

=item C<ip-addresses: array of GuestIpAddress> (optional)

List of addresses assigned to C<name>

=back



B<Since:>
1.1






B<guest-network-get-interfaces>  (Command)
Get list of guest IP addresses, MAC addresses
and netmasks.


B<Returns:>
List of GuestNetworkInfo on success.

B<Since:>
1.1






B<GuestLogicalProcessor> (Object)




B<Members:>

=over 4


=item C<logical-id: int>

Arbitrary guest-specific unique identifier of the VCPU.

=item C<online: boolean>

Whether the VCPU is enabled.

=item C<can-offline: boolean> (optional)

Whether offlining the VCPU is possible. This member
is always filled in by the guest agent when the structure is
returned, and always ignored on input (hence it can be omitted
then).

=back



B<Since:>
1.5






B<guest-get-vcpus>  (Command)
Retrieve the list of the guest's logical processors.

This is a read-only operation.


B<Returns:>
The list of all VCPUs the guest knows about. Each VCPU is put on the
list exactly once, but their order is unspecified.

B<Since:>
1.5






B<guest-set-vcpus>  (Command)
Attempt to reconfigure (currently: enable/disable) logical processors inside
the guest.

The input list is processed node by node in order. In each node C<logical-id>
is used to look up the guest VCPU, for which C<online> specifies the requested
state. The set of distinct C<logical-id>'s is only required to be a subset of
the guest-supported identifiers. There's no restriction on list length or on
repeating the same C<logical-id> (with possibly different C<online> field).
Preferably the input list should describe a modified subset of
C<guest-get-vcpus>' return value.

B<Arguments:>

=over 4


=item C<vcpus: array of GuestLogicalProcessor>

Not documented

=back



B<Returns:>
The length of the initial sublist that has been successfully
processed. The guest agent maximizes this value. Possible cases:


=over 4


=item -

0:              if the C<vcpus> list was empty on input. Guest state
has not been changed. Otherwise,

=item -

Error:          processing the first node of C<vcpus> failed for the
reason returned. Guest state has not been changed.
Otherwise,

=item -

E<lt> length(C<vcpus>): more than zero initial nodes have been processed,
but not the entire C<vcpus> list. Guest state has
changed accordingly. To retrieve the error
(assuming it persists), repeat the call with the
successfully processed initial sublist removed.
Otherwise,

=item -

length(C<vcpus>): call successful.

=back



B<Since:>
1.5






B<GuestDiskBusType> (Enum)


An enumeration of bus type of disks

B<Values:>

=over 4


=item C<ide>

IDE disks

=item C<fdc>

floppy disks

=item C<scsi>

SCSI disks

=item C<virtio>

virtio disks

=item C<xen>

Xen disks

=item C<usb>

USB disks

=item C<uml>

UML disks

=item C<sata>

SATA disks

=item C<sd>

SD cards

=item C<unknown>

Unknown bus type

=item C<ieee1394>

Win IEEE 1394 bus type

=item C<ssa>

Win SSA bus type

=item C<fibre>

Win fiber channel bus type

=item C<raid>

Win RAID bus type

=item C<iscsi>

Win iScsi bus type

=item C<sas>

Win serial-attaches SCSI bus type

=item C<mmc>

Win multimedia card (MMC) bus type

=item C<virtual>

Win virtual bus type
C<file-backed> virtual: Win file-backed bus type

=item C<file-backed-virtual>

Not documented

=back



B<Since:>
2.2; 'Unknown' and all entries below since 2.4






B<GuestPCIAddress> (Object)




B<Members:>

=over 4


=item C<domain: int>

domain id

=item C<bus: int>

bus id

=item C<slot: int>

slot id

=item C<function: int>

function id

=back



B<Since:>
2.2






B<GuestDiskAddress> (Object)




B<Members:>

=over 4


=item C<pci-controller: GuestPCIAddress>

controller's PCI address

=item C<bus-type: GuestDiskBusType>

bus type

=item C<bus: int>

bus id

=item C<target: int>

target id

=item C<unit: int>

unit id

=back



B<Since:>
2.2






B<GuestFilesystemInfo> (Object)




B<Members:>

=over 4


=item C<name: string>

disk name

=item C<mountpoint: string>

mount point path

=item C<type: string>

file system type string

=item C<disk: array of GuestDiskAddress>

an array of disk hardware information that the volume lies on,
which may be empty if the disk type is not supported

=back



B<Since:>
2.2






B<guest-get-fsinfo>  (Command)



B<Returns:>
The list of filesystems information mounted in the guest.
The returned mountpoints may be specified to
C<guest-fsfreeze-freeze-list>.
Network filesystems (such as CIFS and NFS) are not listed.

B<Since:>
2.2






B<guest-set-user-password>  (Command)


B<Arguments:>

=over 4


=item C<username: string>

the user account whose password to change

=item C<password: string>

the new password entry string, base64 encoded

=item C<crypted: boolean>

true if password is already crypt()d, false if raw

=back

If the C<crypted> flag is true, it is the caller's responsibility
to ensure the correct crypt() encryption scheme is used. This
command does not attempt to interpret or report on the encryption
scheme. Refer to the documentation of the guest operating system
in question to determine what is supported.

Not all guest operating systems will support use of the
C<crypted> flag, as they may require the clear-text password

The C<password> parameter must always be base64 encoded before
transmission, even if already crypt()d, to ensure it is 8-bit
safe when passed as JSON.

B<Returns:>
Nothing on success.

B<Since:>
2.3






B<GuestMemoryBlock> (Object)




B<Members:>

=over 4


=item C<phys-index: int>

Arbitrary guest-specific unique identifier of the MEMORY BLOCK.

=item C<online: boolean>

Whether the MEMORY BLOCK is enabled in guest.

=item C<can-offline: boolean> (optional)

Whether offlining the MEMORY BLOCK is possible.
This member is always filled in by the guest agent when the
structure is returned, and always ignored on input (hence it
can be omitted then).

=back



B<Since:>
2.3






B<guest-get-memory-blocks>  (Command)
Retrieve the list of the guest's memory blocks.

This is a read-only operation.


B<Returns:>
The list of all memory blocks the guest knows about.
Each memory block is put on the list exactly once, but their order
is unspecified.

B<Since:>
2.3






B<GuestMemoryBlockResponseType> (Enum)


An enumeration of memory block operation result.

B<Values:>

=over 4


=item C<success>

the operation of online/offline memory block is successful.

=item C<not-found>

can't find the corresponding memoryXXX directory in sysfs.

=item C<operation-not-supported>

for some old kernels, it does not support
online or offline memory block.

=item C<operation-failed>

the operation of online/offline memory block fails,
because of some errors happen.

=back



B<Since:>
2.3






B<GuestMemoryBlockResponse> (Object)




B<Members:>

=over 4


=item C<phys-index: int>

same with the 'phys-index' member of C<GuestMemoryBlock>.

=item C<response: GuestMemoryBlockResponseType>

the result of memory block operation.

=item C<error-code: int> (optional)

the error number.
When memory block operation fails, we assign the value of
'errno' to this member, it indicates what goes wrong.
When the operation succeeds, it will be omitted.

=back



B<Since:>
2.3






B<guest-set-memory-blocks>  (Command)
Attempt to reconfigure (currently: enable/disable) state of memory blocks
inside the guest.

The input list is processed node by node in order. In each node C<phys-index>
is used to look up the guest MEMORY BLOCK, for which C<online> specifies the
requested state. The set of distinct C<phys-index>'s is only required to be a
subset of the guest-supported identifiers. There's no restriction on list
length or on repeating the same C<phys-index> (with possibly different C<online>
field).
Preferably the input list should describe a modified subset of
C<guest-get-memory-blocks>' return value.

B<Arguments:>

=over 4


=item C<mem-blks: array of GuestMemoryBlock>

Not documented

=back



B<Returns:>
The operation results, it is a list of C<GuestMemoryBlockResponse>,
which is corresponding to the input list.

Note: it will return NULL if the C<mem-blks> list was empty on input,
or there is an error, and in this case, guest state will not be
changed.

B<Since:>
2.3






B<GuestMemoryBlockInfo> (Object)




B<Members:>

=over 4


=item C<size: int>

the size (in bytes) of the guest memory blocks,
which are the minimal units of memory block online/offline
operations (also called Logical Memory Hotplug).

=back



B<Since:>
2.3






B<guest-get-memory-block-info>  (Command)
Get information relating to guest memory blocks.


B<Returns:>
C<GuestMemoryBlockInfo>

B<Since:>
2.3






B<GuestExecStatus> (Object)




B<Members:>

=over 4


=item C<exited: boolean>

true if process has already terminated.

=item C<exitcode: int> (optional)

process exit code if it was normally terminated.

=item C<signal: int> (optional)

signal number (linux) or unhandled exception code
(windows) if the process was abnormally terminated.

=item C<out-data: string> (optional)

base64-encoded stdout of the process

=item C<err-data: string> (optional)

base64-encoded stderr of the process
Note: C<out-data> and C<err-data> are present only
if 'capture-output' was specified for 'guest-exec'

=item C<out-truncated: boolean> (optional)

true if stdout was not fully captured
due to size limitation.

=item C<err-truncated: boolean> (optional)

true if stderr was not fully captured
due to size limitation.

=back



B<Since:>
2.5






B<guest-exec-status>  (Command)
Check status of process associated with PID retrieved via guest-exec.
Reap the process and associated metadata if it has exited.

B<Arguments:>

=over 4


=item C<pid: int>

pid returned from guest-exec

=back



B<Returns:>
GuestExecStatus on success.

B<Since:>
2.5






B<GuestExec> (Object)




B<Members:>

=over 4


=item C<pid: int>

pid of child process in guest OS

=back



B<Since:>
2.5






B<guest-exec>  (Command)
Execute a command in the guest

B<Arguments:>

=over 4


=item C<path: string>

path or executable name to execute

=item C<arg: array of string> (optional)

argument list to pass to executable

=item C<env: array of string> (optional)

environment variables to pass to executable

=item C<input-data: string> (optional)

data to be passed to process stdin (base64 encoded)

=item C<capture-output: boolean> (optional)

bool flag to enable capture of
stdout/stderr of running process. defaults to false.

=back



B<Returns:>
PID on success.

B<Since:>
2.5






B<GuestHostName> (Object)




B<Members:>

=over 4


=item C<host-name: string>

Fully qualified domain name of the guest OS

=back



B<Since:>
2.10






B<guest-get-host-name>  (Command)
Return a name for the machine.

The returned name is not necessarily a fully-qualified domain name, or even
present in DNS or some other name service at all. It need not even be unique
on your local network or site, but usually it is.


B<Returns:>
the host name of the machine on success

B<Since:>
2.10






B<GuestUser> (Object)




B<Members:>

=over 4


=item C<user: string>

Username

=item C<domain: string> (optional)

Logon domain (windows only)

=item C<login-time: number>

Time of login of this user on the computer. If multiple
instances of the user are logged in, the earliest login time is
reported. The value is in fractional seconds since epoch time.

=back



B<Since:>
2.10






B<guest-get-users>  (Command)
Retrieves a list of currently active users on the VM.


B<Returns:>
A unique list of users.

B<Since:>
2.10






B<GuestTimezone> (Object)




B<Members:>

=over 4


=item C<zone: string> (optional)

Timezone name. These values may differ depending on guest/OS and
should only be used for informational purposes.

=item C<offset: int>

Offset to UTC in seconds, negative numbers for time zones west of
GMT, positive numbers for east

=back



B<Since:>
2.10






B<guest-get-timezone>  (Command)
Retrieves the timezone information from the guest.


B<Returns:>
A GuestTimezone dictionary.

B<Since:>
2.10






B<GuestOSInfo> (Object)




B<Members:>

=over 4


=item C<kernel-release: string> (optional)


=over 4


=item *

POSIX: release field returned by uname(2)

=item *

Windows: version number of the OS

=back



=item C<kernel-version: string> (optional)


=over 4


=item *

POSIX: version field returned by uname(2)

=item *

Windows: build number of the OS

=back



=item C<machine: string> (optional)


=over 4


=item *

POSIX: machine field returned by uname(2)

=item *

Windows: one of x86, x86_64, arm, ia64

=back



=item C<id: string> (optional)


=over 4


=item *

POSIX: as defined by os-release(5)

=item *

Windows: contains string "mswindows"

=back



=item C<name: string> (optional)


=over 4


=item *

POSIX: as defined by os-release(5)

=item *

Windows: contains string "Microsoft Windows"

=back



=item C<pretty-name: string> (optional)


=over 4


=item *

POSIX: as defined by os-release(5)

=item *

Windows: product name, e.g. "Microsoft Windows 10 Enterprise"

=back



=item C<version: string> (optional)


=over 4


=item *

POSIX: as defined by os-release(5)

=item *

Windows: long version string, e.g. "Microsoft Windows Server 2008"

=back



=item C<version-id: string> (optional)


=over 4


=item *

POSIX: as defined by os-release(5)

=item *

Windows: short version identifier, e.g. "7" or "20012r2"

=back



=item C<variant: string> (optional)


=over 4


=item *

POSIX: as defined by os-release(5)

=item *

Windows: contains string "server" or "client"

=back



=item C<variant-id: string> (optional)


=over 4


=item *

POSIX: as defined by os-release(5)

=item *

Windows: contains string "server" or "client"

=back



=back



B<Notes:>
On POSIX systems the fields C<id>, C<name>, C<pretty-name>, C<version>, C<version-id>,
C<variant> and C<variant-id> follow the definition specified in os-release(5).
Refer to the manual page for exact description of the fields. Their values
are taken from the os-release file. If the file is not present in the system,
or the values are not present in the file, the fields are not included.

On Windows the values are filled from information gathered from the system.

B<Since:>
2.10






B<guest-get-osinfo>  (Command)
Retrieve guest operating system information


B<Returns:>
C<GuestOSInfo>

B<Since:>
2.10






