/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu-common.h"
#include "cpu.h"
#include "exec/helper-proto.h"
#include "trace-root.h"

void helper_trace_guest_mem_before_exec_proxy(CPUArchState * __tcg___cpu, target_ulong vaddr, uint32_t info)
{
    _nocheck__trace_guest_mem_before_exec((CPUState *)ENV_GET_CPU(__tcg___cpu), (uint64_t)vaddr, (uint8_t)info);
}
